version: v1.3
tools:
  - subclass: WDL
    primaryDescriptorPath: samtools_manta.wdl
    testParameterFiles: inputs.json
    authors:
      - name: Sai Mukund Ramakrishnan
        email: saimukund@wustl.edu
